name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # Configura o Node.js
      - name: Configura o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instala dependências
      - name: Instala dependências
        run: npm install

      # Executa o servidor (opcional, dependendo do deploy)
      - name: Executa o servidor
        run: node server.js
