name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Configura o Node.js
      - name: Configura o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Verifica arquivos no repositório
      - name: Listar arquivos no repositório
        run: ls -la

      # 4. Instala dependências
      - name: Instala dependências
        run: npm install
        working-directory: ./

      # 5. Executa o servidor (opcional)
      - name: Executa o servidor
        run: node server.js
